// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIQQAXh4Bphb9wffnJBWYnF5FEBoDUXTg',
    appId: '1:355624963520:android:7e56bc98cac6504325cc25',
    messagingSenderId: '355624963520',
    projectId: 'sivia-284f1',
    storageBucket: 'sivia-284f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXbpSoTHEcJDd2NNIns094JjtMco5M28g',
    appId: '1:355624963520:ios:44f732fe39ac413a25cc25',
    messagingSenderId: '355624963520',
    projectId: 'sivia-284f1',
    storageBucket: 'sivia-284f1.firebasestorage.app',
    iosBundleId: 'com.example.incaucaLabs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdXrwbg6eKadF-lYfarD___HOKhjX4MOk',
    appId: '1:355624963520:web:4feaab74127bdc1625cc25',
    messagingSenderId: '355624963520',
    projectId: 'sivia-284f1',
    authDomain: 'sivia-284f1.firebaseapp.com',
    storageBucket: 'sivia-284f1.firebasestorage.app',
    measurementId: 'G-QTQQ3X08HY',
  );
}
